### ISSUE TITLE
pymake-created makefile for building shared lib

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/pymake#104]
Hey guys - Im not sure if Im doing this right, but im trying to get makefile from pymake that I can use to build the shared lib on linux.  I added `pm.makefile=True` in `mf6/autotest/build_exes.py.build_mf6_so()` and I get a makefile and a makedefault, but they dont make it thru the build (haha - make) - all the objects get compiled, but the linker dies:

```
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
```

pymake itself has no trouble building.  Im sure this is user error - any idea what Im doing wrong?

**Comment by jdhughes-usgs** [comment]
I have never tested the make file with the shared object. I see that it is setting the flags for the standard mf6 executable.

Change the compiler and linker flags in `makedefault` to 

```
# set the fortran flags
ifeq ($(detected_OS), Windows)
	ifeq ($(FC), gfortran)
		FFLAGS ?= -fPIC -fbacktrace -ffpe-summary=overflow -ffpe-trap=overflow,zero,invalid $(OS_macro) -Wtabs -Wline-truncation -Wunused-label -Wunused-variable -pedantic -std=f2008 -Wcharacter-truncation -cpp
	endif
else
	ifeq ($(FC), gfortran)
		FFLAGS ?= -fPIC -fbacktrace -ffpe-summary=overflow -ffpe-trap=overflow,zero,invalid $(OS_macro) -Wtabs -Wline-truncation -Wunused-label -Wunused-variable -pedantic -std=f2008 -Wcharacter-truncation -cpp
	endif
	ifeq ($(FC), $(filter $(FC), ifort mpiifort))
		FFLAGS ?= -no-heap-arrays -fpe0 -traceback -fpp
		MODSWITCH = -module $(MODDIR)
	endif
endif

# set the ldflgs
ifeq ($(detected_OS), Windows)
	ifeq ($(FC), $(filter $(FC), gfortran))
		LDFLAGS ?= -shared -lm
	endif
else
	ifeq ($(FC), gfortran)
		LDFLAGS ?= -shared -lc
	endif
	ifeq ($(FC), $(filter $(FC), ifort mpiifort))
		LDFLAGS ?= -lc
	endif
endif
```

This works for `gfortran` but is not correct for `ifort`.

I will address the makefile flags as soon as I can get to it.

**Comment by jtwhite79** [comment]
thanks @jdhughes-usgs !  It looks like its just the `-shared` linker flag that is missing (duh!  sorry shouldnt been able to sort that!)
