### ISSUE TITLE
ImportError: cannot import name 'is_exe'

### ISSUE THREAD

**Issue by s-scherrer** [modflowpy/pymake#11]
I just tried to install pymake, but unfortunately it didn't work.

I think the line in pymake.py
`from flopy import is_exe ...`
should be
`from flopy.mbase import is_exe ...`

**Comment by jdhughes-usgs** [comment]
You have to pull the latest version of the development branch of flopy and pymake (the call you list is different in the [latest pymake commit](https://github.com/modflowpy/pymake/commit/1d6257c953eab81cf5f3165ec59bd3a60611f78a) .
