### ISSUE TITLE
No gsflow make capabilites?

### ISSUE THREAD

**Issue by boatmorrow** [modflowpy/pymake#150]
Hello,  as of last year I could make gflow using the make_gsflow.py script, which seems to have left the repository now.  I tried using the make-program utility and get the following:

make-program gsflow -fc=gfortran --fflags='-O3'
Traceback (most recent call last):
  File "/Users/payton.gardner/soft/FlopyTothDemo/.conda/bin/make-program", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/payton.gardner/soft/FlopyTothDemo/.conda/lib/python3.11/site-packages/pymake/cmds/build.py", line 140, in main
    build_apps(**args)
  File "/Users/payton.gardner/soft/FlopyTothDemo/.conda/lib/python3.11/site-packages/pymake/pymake_build_apps.py", line 146, in build_apps
    code_dict[target] = usgs_program_data.get_target(target)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/payton.gardner/soft/FlopyTothDemo/.conda/lib/python3.11/site-packages/pymake/utils/usgsprograms.py", line 198, in get_target
    return usgs_program_data()._target_data(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/payton.gardner/soft/FlopyTothDemo/.conda/lib/python3.11/site-packages/pymake/utils/usgsprograms.py", line 144, in _target_data
    raise KeyError(msg)
KeyError: '"gsflow" key does not exist. Available keys: "mf6", "zbud6", "libmf6", "mp7", "mt3dms", "mt3dusgs", "vs2dt", "triangle", "gridgen", "crt", "sutra", "mf2000", "mf2005", "mfusg", "zonbudusg", "swtv4", "mp6", "mflgr", "zonbud3", "mfnwt1.1.4", "mfnwt", "mfusg_gsi"'

Looks, like gsflow is no longer a make target?  Is there any reason?  If not, can we get the make_gflow.py script back?

Thanks,
Payton

**Comment by wpbonelli** [comment]
@boatmorrow support for gsflow and prms was removed with [version 1.2.6](https://github.com/modflowpy/pymake/pull/123/files#diff-ed637c60039d9c23ade6212715ab369637c6ce4b62443026042fffe13465fba5), I just updated the [release notes](https://github.com/modflowpy/pymake/releases/tag/1.2.6) to reflect this. I don't know the details of this decision, maybe @jdhughes-usgs can comment

**Comment by boatmorrow** [comment]
Ok.  I guess this is just a mac specific issue, since there are binaries for Windows and Linux.  For the record, if case anyone else has this problem in the future. I built from source using the provided makefile in the linux software release on my mac arm64 using gcc13.  It appears to have worked fine.  I haven't checked all tests yet, but is passing all that I've check so far.

**Comment by jdhughes-usgs** [comment]
@boatmorrow gsflow pymake builds have been included again (version 1.2.9). We have included version 2.2.1 since this is the version recommended on the USGS website. Historically, the gsflow distribution has been messy and has required cleanup before it could be built with pymake. New versions gsflow may not be included in the future.
