### ISSUE TITLE
Help: AssertionError: Target does not exist.

### ISSUE THREAD

**Issue by yodges** [modflowpy/pymake#16]
When I run make_mf2005.py I get the following error and the target file 'mf2005dbl' is never created.

Traceback (most recent call last):
    File "make_mf2005.py", line 42, in <module>
        make_mf2005()
    File "make_mf2005.py", line 35, in make_mf2005
        assert os.path.isfile(target), 'Target does not exist.'
AssertionError: Target does not exist.

Can you think of any reason(s) why there is no mf2005dbl file? MF2005.1_12.u gets downloaded and placed in a folder 'temp' but I can't think of what is wrong to cause the file never to be written to the path (sorry, newbie)

**Comment by langevin-usgs** [comment]
Would need more information from you.  Are you running on a Mac?  Do you have gfortran installed?

**Comment by yodges** [comment]
Yes, I am on Mac version 10.12 and I believe gfortran is installed, here is what happens when I enter gfortran --version in the terminal:
gfortran: warning: couldn’t understand kern.osversion ‘16.6.0
GNU Fortran (GCC) 4.9.0
Copyright (C) 2014 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

**Comment by langevin-usgs** [comment]
The mf2005 unix distribution (the one that is downloaded when you run the make_mf2005.py script) comes with a make file.  Can you open a terminal window in the make folder and type "make".  It should compile with gfortran.  If this doesn't work, then I suspect gfortran is not configured correctly on your mac.  I install gfortran on my mac using Macports, but I'm sure there are other ways to get it installed properly.

**Comment by yodges** [comment]
Awesome, after updating xcode, gfortran and the "make" command seems to have worked. There's still a bunch of warnings (ld: warning: object file (./obj_temp/mf2005.o) was built for newer OSX version (10.12) than being linked (10.4), could this be something wrong with the makefile, or with gfortran not being installed/updated correctly? I changed the compile flags in the makefile before as directed by https://adamsgaard.dk/files/MODFLOW-OSX-Installation-Guide.pdf

Thanks so much for the help and the quick response!
