### ISSUE TITLE
urllib.error.ContentTooShortError

### ISSUE THREAD

**Issue by spencerbh** [modflowpy/pymake#17]
It takes several tries for the modflow2000 example, make_mf2000.py, script to download the associated tar.gz file. Link seems fine if downloading in a web-browser though. Took me about 6 tries before I got a successful download. Not sure where the issue is. Pic is of full error code. Thanks
![image](https://user-images.githubusercontent.com/16962098/27154325-a965a6ca-5122-11e7-96e1-3f0301da4753.png)

**Comment by jdhughes-usgs** [comment]
I have encountered issues downloading the installation files. I usually do what you did and wait some time before trying again. I am not sure there is an easy solution to this problem. We will put this on our list of improvements.
