### ISSUE TITLE
module directory

### ISSUE THREAD

**Issue by mwtoews** [modflowpy/pymake#18]
Both Intel Fortran (ifort) and Portland Group Fortran (pgfortran) use `-module dir` to describe the directory where module files files should be placed when created and where  they should be searched for.

This is in contrast to GNU Fortran, which uses the `-Jdir` directive to describe the same feature, and is currently hard-coded to pymake.py

I can think of two ways to address this difference: one in the Makefile using variables, and the other by modifying pymake.py to produce different output depending on the options. (On a related note, I've also been thinking that a PyMake class should be created in pymake.py to provide OOP conveniences in creating objects for (e.g.) GNU and Intel compilers on POSIX or Win32 platforms, or create target rules only if certain source files are found.)

**Comment by jdhughes-usgs** [comment]
@mwtoews I think the makefile issue with recent changes. Also I recently added a Pymake() object and it would be good to get any suggestions that you may have on improving the class. I will open an issue asking for feedback on the Pymake() class.
