### ISSUE TITLE
Compile seawat4 on Ubuntu 14.04

### ISSUE THREAD

**Issue by arjenoord** [modflowpy/pymake#2]
Hello,

I am trying to use pymake to compile seawat v4 (Ubuntu 14.04.2). Unfortunately I have run into some errors. One I have not been able to resolve yet:

gfortran -O2 -c ./src_temp/parallel/para-mpi.f -o ./obj_temp/para-mpi.o -Iobj_temp -Jmod_temp 
./src_temp/parallel/para-mpi.f:15: Error: Can't open included file 'mpif.h'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymake.py", line 342, in main
    expedite, dryrun)
  File "pymake.py", line 232, in compile_with_gnu
    subprocess.check_call(cmdlist)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gfortran', '-O2', '-c', './src_temp/parallel/para-mpi.f', '-o', './obj_temp/para-mpi.o', '-Iobj_temp', '-Jmod_temp']' returned non-zero exit status 1

Any ideas?

Much appreciated.

Regards,
Arjen

**Comment by langevin-usgs** [comment]
Hi Arjen, I had to rework pymake a bit to have it compile SEAWAT automatically.  Take a look at the make_swtv4.py example.  It works for me, and compiles SEAWAT.  The issue that you were having was because of the 'parallel' and 'serial' folders included with source.  The make_swtv4.py script removes these automatically.  Should all work now.  Good luck!

**Comment by arjenoord** [comment]
Hi 
Got it! I still had to rename a few files that have file names in capitals (e.g. SOLVERS.c), but after that, no problem! The automatic download is quite convenient.
Thanks.
Arjen

**Comment by langevin-usgs** [comment]
Strange that there are still problems with the capital letter file names. I thought I fixed that in pymake by converting to lower when building the DAG. I don't have a problem on my Mac. Let me know if come across a fix for that.
