### ISSUE TITLE
using pymake without setup.py

### ISSUE THREAD

**Issue by jtwhite79** [modflowpy/pymake#24]
Is there some trick to using pymake without having to first run ``setup.py install``?  I've got it plumbed up in site-package pth file, but when I import pymake, I get an "ImportError python attempted relative import with no known parent package" coming from the ``from .dag `` line in ``__init__.py``.

**Comment by langevin-usgs** [comment]
I also have it plumbed up in a site-package pth file, but I can "import pymake" without any problems on both windows and mac with python 3.6.3 and 3.6.4.

**Comment by jtwhite79** [comment]
Should have mentioned this prob is on fedora 26.  I also have it path'd on Mac no prob.
