### ISSUE TITLE
compile modflow 2005 on a mac-errors?

### ISSUE THREAD

**Issue by Neilt100** [modflowpy/pymake#3]
Hi.  I've compiled MODFLOW 2005 using pymake succesfully, but when I run modflow (using the example model files) I get the following message:

/MF2005.1_11u/test-run/mf2005dbl ; exit;

                                  MODFLOW-2005     
    U.S. GEOLOGICAL SURVEY MODULAR FINITE-DIFFERENCE GROUND-WATER FLOW MODEL
                             Version 1.11.00 8/8/2013                        

  Enter the name of the NAME FILE: 
mf2005.1_11u/test-run/bcf2ss
 Using NAME file: mf2005.1_11u/test-run/bcf2ss.nam 
 Run start date and time (yyyy/mm/dd hh:mm:ss): 2015/09/22 22:36:36

 *** ERROR OPENING FILE "bcf2ss.ba6" ON UNIT     8
       SPECIFIED FILE STATUS: OLD    
       SPECIFIED FILE FORMAT: FORMATTED           
       SPECIFIED FILE ACCESS: SEQUENTIAL          
       SPECIFIED FILE ACTION: READ                
  -- STOP EXECUTION (SGWF2BAS7OPEN)
logout

[Process completed]

Does anyone have any suggestions for what causes this error message?  The compile process ran with 6 warnings, similar to:

\\./src_temp/mf2kgmg.c:164:29: warning: cast to 'MF2KGMG_operator *' (aka 'struct
      MF2KGMG_operator *') from smaller integer type 'int'
      [-Wint-to-pointer-cast]
  MF2KGMG_operator* GMG_ptr=(MF2KGMG_operator*)*GMGID;

I've also tried compiling using the makefile supplied with the source code, but I end up with the same error message from the compiled MODFLOW executable.  I'm using a macbook pro running OSX10.10.

Many thanks.

**Comment by langevin-usgs** [comment]
It looks like you may not be running MODFLOW from within the test-run folder.  Make sure you change to that directory, and then run MODFLOW.  That GMG error is something that we are aware of.  It will be fixed in the next MODFLOW release.

**Comment by Neilt100** [comment]
Hi,

Many thanks for the reply, but I still get the same error, even where I copy the executable into the test-run folder and run it from there: 
       /MF2005.1_11u/test-run/mf2005dbl ; exit;

                                  MODFLOW-2005     
    U.S. GEOLOGICAL SURVEY MODULAR FINITE-DIFFERENCE GROUND-WATER FLOW MODEL
                             Version 1.11.00 8/8/2013                        

      Enter the name of the NAME FILE: 
     /users/neilthomas/downloads/pymake-master/pymake/mf2005.1_11u/test-run/twrip.nam
     Using NAME file: /users/neilthomas/downloads/pymake-master/pymake/mf2005.1_11u/test-run/twrip.nam 
     Run start date and time (yyyy/mm/dd hh:mm:ss): 2015/09/23 19:37:47


     *** ERROR OPENING FILE "twrip.ba6" ON UNIT     3
       SPECIFIED FILE STATUS: OLD    
       SPECIFIED FILE FORMAT: FORMATTED           
       SPECIFIED FILE ACCESS: SEQUENTIAL          
       SPECIFIED FILE ACTION: READ                
     -- STOP EXECUTION (SGWF2BAS7OPEN)
    logout


    [Process completed]

**Comment by Neilt100** [comment]
Hi,

This now works- my version of modflow was running under a different directory.  Many thanks for your help.

Cheers.
