### ISSUE TITLE
compile flag -ffpe-summary isn't available in all gfortran 

### ISSUE THREAD

**Issue by collord** [modflowpy/pymake#5]
It appears that after a certain version, -ffpe-summary compiler flag isn't available in gfortran. 

mfusg appears to build with gfortran 4.6.3 on ubuntu precise x86_64 with the removal of this flag. I'm not sure what the implications are though.

**Comment by langevin-usgs** [comment]
Okay, thanks for letting us know about this.  I believe this flag just provides some additional information if the program bombs.  I don't remember whey we added this to pymake.

**Comment by jdhughes-usgs** [comment]
This issue should be fixed now. Tested on gfortran 4.4.7.

**Comment by collord** [comment]
@jdhughes-usgs thanks.
