### ISSUE TITLE
malloc error running mf6.2 on mac

### ISSUE THREAD

**Issue by bafleck** [modflowpy/pymake#90]
Hi,

I have a problem with mf6.2 on my mac:

I compiled it  with pymake_mf6.py, using gfortran 5.2.0

When trying to run a program with the new mf6 I get the message:

mf6(21895,0x7fff77256300) malloc: *** error for object 0x7faeb1e01458: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug

Program received signal SIGABRT: Process abort signal.

Backtrace for this error:
#0  0x103b10092
#1  0x103b0f3b0
#2  0x7fff8ba19f19

Can you please help me.

Thanks
Barbara Fleck (barbarafleck56@gmail.com

**Comment by langevin-usgs** [comment]
Really hard to say what the problem is.  It's probably an input error, unless you know this model runs with other compiled versions.  Have you tried the executable here: https://github.com/MODFLOW-USGS/executables?

**Comment by bafleck** [comment]
Thank you, this mac-executable is ok.
regards
Barbara
