### ISSUE TITLE
Could you please offer me the swtv4?

### ISSUE THREAD

**Issue by Xin-Start** [modflowpy/pymake#91]
My personal computer is Windows, and I hope to gain an executable file to run my Seawat model on HPC which is based on Linux system. 

When I run the example file (make_swtv4.py) on my personal computer, there comes an error, and I don't know how to deal with it. So can someone offer me the swtv4 file that can be run on the Linux system?
Thanks for your help!

**Comment by jtwhite79** [comment]
I think you can get portable-ish linux binaries here: https://github.com/MODFLOW-USGS/executables

**Comment by Xin-Start** [comment]
> I think you can get portable-ish linux binaries here: https://github.com/MODFLOW-USGS/executables

Thank you so much! I really appreciate it.
