### ISSUE TITLE
Trying to use pymake for MODPATH 7: AttributeError: module 'pymake.pymake' has no attribute 'parser'.

### ISSUE THREAD

**Issue by Matt-Webb1** [modflowpy/pymake#93]
When I try to use the makebin.bat file included with [Modpath-7](https://github.com/MODFLOW-USGS/modpath-v7/tree/develop) to run run makebin.py I get the error: 

```
args = pymake.pymake.parser()
AttributeError: module 'pymake.pymake' has no attribute 'parser'

```

When I run `pip list` it shows that pymake 1.2.1 is installed (it previously wasn't and the output from makebin.py instructed me to do so). Any suggestions for what I might be doing wrong? I was hoping to recompile with [this commit](https://github.com/MODFLOW-USGS/modpath-v7/commit/f382506f094805d0e3bbc917ffb0c7cbe5cb91bd) included so that I can use MP7 on a grid that didn't meet the unnecessarily strict criteria.

**Comment by jlarsen-usgs** [comment]
@Matt-Webb1 

It looks like this issue should be raised in the Modpath-7 github repo. The makebin.py script needs to be updated.

If you open `makebin.py` and change line 13 from
`args = pymake.pymake.parser()` to `args = pymake.parser()`

and change line 17 from
`pymake.pymake.main(.......` to `pymake.main(........` 

the code should work

**Comment by Matt-Webb1** [comment]
Thanks @jlarsen-usgs ! I tired that and I get a different error now:

```
F:\Matt\Downloads\modpath-v7-develop\modpath-v7-develop\pymake>python makebin.py -fc ifort -mc -ar intel64 ../source mpath7.exe
Traceback (most recent call last):
  File "makebin.py", line 17, in <module>
    pymake.main(args.srcdir, args.target, args.fc, args.cc, args.makeclean,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 256, in main
    returncode = _pymake_compile(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 759, in _pymake_compile
    lc, tlflags = _get_linker_flags(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\utils\_compiler_switches.py", line 684, in _get_linker_flags
    for idx, flag in enumerate(syslibs[1:]):
TypeError: 'bool' object is not subscriptable

F:\Matt\Downloads\modpath-v7-develop\modpath-v7-develop\pymake>python makebin.py -fc ifort -mc -ar ia32 ../source mpath7_win32.exe
Traceback (most recent call last):
  File "makebin.py", line 17, in <module>
    pymake.main(args.srcdir, args.target, args.fc, args.cc, args.makeclean,
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 256, in main
    returncode = _pymake_compile(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\pymake_base.py", line 759, in _pymake_compile
    lc, tlflags = _get_linker_flags(
  File "C:\ProgramData\Anaconda3\lib\site-packages\pymake\utils\_compiler_switches.py", line 684, in _get_linker_flags
    for idx, flag in enumerate(syslibs[1:]):
TypeError: 'bool' object is not subscriptable

F:\Matt\Downloads\modpath-v7-develop\modpath-v7-develop\pymake>pause
Press any key to continue . . .
```
I'm trying to look into that now.

**Comment by jlarsen-usgs** [comment]
@Matt-Webb1 

Just linked this issue to the modpath-v7 repository. Please follow up there for solutions.

**Comment by Matt-Webb1** [comment]
Thanks!
